### ISSUE TITLE
Harmonie cy40 model is replaced by cy43

### ISSUE THREAD

**Issue by tweerwag** [alliander-opensource/Weather-Provider-API#138]
**Describe the bug**
The harmonie cy40 model is deprecated and has not been updated after 31 August. It was replaced by cy43. See https://developer.dataplatform.knmi.nl/deprecation-harmonie-arome-cy40 and https://www.knmidata.nl/actueel/nieuwsbrieven/open-data-nieuwsbrief/2024/open-data-februari-2024 . Current model is https://dataplatform.knmi.nl/dataset/preview/harmonie-arome-cy43-p1-1-0 .

**To Reproduce**
Request arome data from the weather api.

**Expected behavior**
Arome forecast is returned.

**Comment by rflinnenbank** [comment]
Good afternoon!

Our apologies! 
We'd already written an fix to deal with this replacement, but due to having to verify the proper working of the new version, we'd not updated the main branch as of yet. We intend to push the new version before the day is through!

**Comment by rflinnenbank** [comment]
**Release 2.57.048** and up should update the Harmonie AROME data to use the newer version. Because of the much higher resolution in data, for now we'll pin the downloads to only the same 4 6-hourly files as before to prevent data storage sizes from exploding.

In the near future we'll aim to properly address and process this change. 

**With kind regards,**

Raoul Linnenbank

**Comment by rflinnenbank** [comment]
Because the most recent update has set system to use the newer CY43 version, we'll consider this issue to be closed.

As indicated, we do intend to address the differences between the older and newer versions of Harmonie AROME in the near future.
